### ISSUE TITLE
Exceptions when signing in

### ISSUE THREAD

**Issue by Criccle** [swkruger/Mendix-MSGraphConnector#2]
I am receiving the following error when authenticating my application:

![image](https://user-images.githubusercontent.com/10046210/28824738-d71705f2-76c3-11e7-9016-a1617a5deb26.png)

After I click the URL bar and press Enter to trigger the requesthandler again, the following errors are printed to the console:

`Exception occurred while processing request java.net.SocketException: Connection reset by peer: socket write error`

`An error occured when creating the AuthToken record. /n[Ljava.lang.StackTraceElement;@2f227ecc`

Somewhere inbetween these error messages I also get: 

`Cookie not found`

Any idea what I'm doing wrong?

**Comment by Criccle** [comment]
Created pull request for this issue, refres token was being set where it wasn't returned by the webservice

**Comment by swkruger** [comment]
Hi Criccle, 

Thanks for your interest, I will look at the pull request asap.

**Comment by swkruger** [comment]
New release 1.0.1-beta available with AuthTokenHandler.java updates
